MovieShopMVC/Models/ErrorViewModel.cs
using System;

namespace MovieShopMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieShopMVC/Controllers/AccountController.cs
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class AccountController : Controller
    {
        private readonly IUserService _userService;

        public AccountController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterRequestModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var createUser = await _userService.RegisterUser(model);

            return RedirectToAction("Login");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }



        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(UserLoginRequestModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = await _userService.Login(model.Email, model.Password);

            if (user == null)
            {
                // wrong password
                ModelState.AddModelError(string.Empty, "Invalid password");
                return View();
            }

            var claims = new List<Claim>
            {
                 new Claim(ClaimTypes.Email, user.Email),
                 new Claim(ClaimTypes.GivenName, user.FirstName),
                 new Claim(ClaimTypes.Surname, user.LastName),
                 new Claim(ClaimTypes.NameIdentifier, user.Id.ToString())
            };

            // identity object

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            // create the cookie
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

            return LocalRedirect("~/");



        }
    }
}

MovieShopMVC/Controllers/CastController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace MovieShopMVC.Controllers
{
    public class CastController : Controller
    {
        private readonly ICastService _castService;


        public CastController(ICastService castService)
        {
            _castService = castService;
        }
        public async Task<IActionResult> Details(int id)
        {
            var cast = await _castService.GetMovieByCast(id);
            return View(cast);
        }
    }
}

MovieShopMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieShopMVC.Models;
using Infrastructure.Services;
using ApplicationCore.ServiceInterfaces;

namespace MovieShopMVC.Controllers
{
    public class HomeController : Controller
    {
    

        private readonly IMovieService _movieService;

        public HomeController(IMovieService movieService)
        {
            _movieService = movieService;

        }

        public IActionResult Privacy()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            var movies = await _movieService.GetTopRevenueMovies();
            return View(movies);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieShopMVC/Controllers/MoviesController.cs
using System.Threading.Tasks;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;
      

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

      
        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieService.GetMovieDetails(id);
            return View(movie);
        }

        public async Task<IActionResult> Genre(int id)
        {

            var movie = await _movieService.GetfilterGenres(id);
            return View(movie);
        }

        public async Task<IActionResult> Cast(int id)
        {

            var movie = await _movieService.GetMovieByCast(id);
            return View(movie);
        }


    }
}

MovieShopMVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class UserController : Controller
    {
        public IActionResult ConfirmPurchase()
        {
            return View();
        }
    }
}

MovieShopMVC/Views/Cast/Details.cshtml
@section styles {
    <link rel="stylesheet" href="~/css/cast.css" />
}
@model ApplicationCore.Models.CastResponseModel


<div class="row profile">
    <div class="col-3">
        <img src="@Model.ProfilePath" alt="@Model.Name" />

        <ul class="list-group">
            <li class="ProfileTitle">Profile</li>
            <li class="infoTitle">Name</li>
            <li class="info">@Model.Name</li>
            <li class="infoTitle">Products Count</li>
            <li class="info">@Model.MovieCardResponseModel.Count</li>
            <li class="infoTitle"> More info</li>
            <li class="info"><a href=@Model.TmdbUrl/></li>
        </ul>

    </div>
    <div class="col-8">
        <h1>Movie Products</h1>
        <div class="row">

            @foreach (var movie in @Model.MovieCardResponseModel)
            {
                <div class="col-3">
            
                    <partial name="_MovieCard" model="movie" />

                </div>
            }
        </div>

    </div>

</div>

MovieShopMVC/Views/Home/Index.cshtml
@model List<ApplicationCore.Models.MovieCardResponseModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="rounded">
    <div class="container-fluid bg-light">
        <div class="row">
            
           @foreach(var movie in Model)
            {
               <div class="col-3">
                   <partial name="_MovieCard" model="movie"/>
                    
                   @*The second way to call partial view
                   @await Html.PartialAsync("_MovieCard",movie)*@ 
               </div>
            }
        </div>

    </div>
</div>

MovieShopMVC/Views/Movies/Cast.cshtml
@model List<ApplicationCore.Models.MovieCardResponseModel>
@{
    ViewData["Title"] = "Cast Page";
}

<div class="rounded">
    <div class="container-fluid bg-light">

        

    </div>
</div>

MovieShopMVC/Views/Movies/Details.cshtml
@section styles {
    <link rel="stylesheet" href="~/css/details.css"/>
}

@model ApplicationCore.Models.MovieDetailsResponseModel


<div>
   
    <div class="row align-items-center" style="background-image:url(@Model.BackdropUrl);  background-position: center;">
        <div class="col-3 mt-5">
            <partial name="_MovieCard" model="@Model.MovieCardResponseModel" />
        </div>
        <div class="col-6">
            <h1>@Model.Title</h1>
            <h6>@Model.Tagline</h6>
            <span>@Model.RunTime</span>
            <span>m</span>


            <ul>
                @foreach (var genre in @Model.Genres)

                {
                    <li><span class="badge badge-secondary">@genre.Name</span></li>
                }
            </ul>
            <span class="badge badge-warning">@Model.Rating</span>
            <p>@Model.Overview</p>

        </div>
        <div class="col-3">
            <button type="button" class="btn btn-outline-light">REVIEW</button>
            <button type="button" class="btn btn-outline-light">TRAILER</button>
            <button type="button" class="btn btn-light">BUY 9.90</button>
            <button type="button" class="btn btn-light">WATCH MOVIE</button>

        </div>

    </div>


    <div class="row movieContent">
        <div class="col-3 movieFacts">
            <ul>
                <li><h4>MOVIE FACTS</h4></li>
                <li><i class='far fa-calendar-alt'></i>
                    Release Date
                    <span class="badge badge-dark"> @Model.ReleaseDate</span>
                   
                </li>
                <li>
                    Run Time
                    <span class="badge badge-dark">  @Model.RunTime m</span>
                  
                </li>
                <li>
                    Box Office
                    <span class="badge badge-dark"> $$ @Model.Revenue</span>
                    
                </li>
                <li>
                    Budget
                    <span class="badge badge-dark"> $$ @Model.Budget</span>
                    
                </li>
            </ul>

        </div>
        <div class="col-6 eachCast offset-1">
            @foreach (var cast in @Model.Casts)
            {
                <div class="row mt-5">
                    <div class="col-1">
                        <a asp-controller="Cast" asp-action="Details" asp-route-id="@cast.Id">
                            <img src="@cast.ProfilePath" class="img-fluid" alt="@cast.Name" />
                        </a>
                    </div>
                    <div class="col-3">@cast.Name</div>
                    <div class="col-7">@cast.Character</div>

                </div>
             }




           
        </div>
    </div>
   
    

</div>


MovieShopMVC/Views/Movies/Genre.cshtml
@model List<ApplicationCore.Models.MovieCardResponseModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="rounded">
    <div class="container-fluid bg-light">
      
        <div class="row">
          

            @foreach (var movie in @Model)
            {
                <div class="col-3">
                    
                    <partial name="_MovieCard" model="movie" />
         
                </div>
            }
        </div>

    </div>
</div>

MovieShopMVC/Views/Shared/_GenresView.cshtml
@using ApplicationCore.ServiceInterfaces

@inject IGenreService _genreService


@foreach (var genre in await _genreService.GetAllGenres())
{
    @*@Html.ActionLink(genre.Name, "Genre", "Movies", new { genreId = genre.Id }, new { @class = "dropdown-item" })*@

    <a asp-controller="Movies" asp-action="Genre" class="dropdown-item" asp-route-id="@genre.Id"> @genre.Name</a>
}

MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav mr-auto text-uppercase">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Genres
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <partial name="_GenresView" />
                            </div>

                        </li>
                    </ul>

                </div>
                <partial name="_LoginPartial" />

            </div>
            
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">

            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieCardResponseModel

<div class="card mb-4 shadow bg-light">
    
        <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
            <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
        </a>
   
    
</div>